In [1]:
import numpy as np

In [2]:
x = [1,5,3,7]

In [3]:
list = np.array(x,np.int32)

In [4]:
list

array([1, 5, 3, 7])

In [5]:
print(list)

[1 5 3 7]


In [6]:
xy = [[2,4,23,5],[4,3,7,8]]

In [7]:
list2D = np.array(xy,np.int64)

In [8]:
list2D

array([[ 2,  4, 23,  5],
       [ 4,  3,  7,  8]], dtype=int64)

# Creating the special arrays

In [9]:
zeros = np.zeros((3,5))

In [10]:
zeros


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

ones = np.ones((3,5))

In [11]:
orange = np.arange(12)

In [12]:
orange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [13]:
linespace = np.linspace(0,10,5)

In [14]:
linespace

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

# Accessing array element

In [15]:
arr = np.array([1,4,3,5,7,4])

In [16]:
arr[4]

7

In [17]:
arr[1:4]

array([4, 3, 5])

In [18]:
arr[::2]

array([1, 3, 7])

# Array Attributes

In [19]:
list3 = [[3,56,3],[9,6,3],[4,34,7]]

In [20]:
array = np.array(list3)

In [21]:
array.shape

(3, 3)

In [22]:
array.dtype

dtype('int32')

In [23]:
array.ndim  #tells the dimensios of array

2

In [24]:
array.size

9

# Basic Operations on array

In [25]:
arr1 = np.array([4,2,6])

In [26]:
arr2 = np.array([4,6,3])

In [27]:
arr1 + arr2

array([8, 8, 9])

In [28]:
arr1 -arr2

array([ 0, -4,  3])

In [29]:
arr1 * arr2

array([16, 12, 18])

In [30]:
arr1 /arr2

array([1.        , 0.33333333, 2.        ])

# Arethmetic Operations

In [31]:
arr1

array([4, 2, 6])

In [32]:
arr1 + 5

array([ 9,  7, 11])

In [33]:
arr1*2

array([ 8,  4, 12])

# Accessing and modifing Array Element

In [34]:
arr1

array([4, 2, 6])

In [35]:
arr1[2]

6

In [36]:
arr1[2] =10

In [37]:
arr1

array([ 4,  2, 10])

# Slicing array to extract subset

In [38]:
ar = np.array([2,5,3,7,9,6,44,55])

In [39]:
ar[:5]

array([2, 5, 3, 7, 9])

In [40]:
ar[2:6]

array([3, 7, 9, 6])

In [41]:
ar[3:]

array([ 7,  9,  6, 44, 55])

In [42]:
ar[1:6:2]

array([5, 7, 6])

In [43]:
ar[::-1]

array([55, 44,  6,  9,  7,  3,  5,  2])

# Array reshaping

In [44]:
ar

array([ 2,  5,  3,  7,  9,  6, 44, 55])

In [45]:
ar.reshape(2,4)

array([[ 2,  5,  3,  7],
       [ 9,  6, 44, 55]])

In [46]:
ar.reshape(4,2)

array([[ 2,  5],
       [ 3,  7],
       [ 9,  6],
       [44, 55]])

In [47]:
ar.reshape(2,1,4)

array([[[ 2,  5,  3,  7]],

       [[ 9,  6, 44, 55]]])

In [48]:
ar.reshape(8)

array([ 2,  5,  3,  7,  9,  6, 44, 55])

In [49]:
ar.reshape(4,-1)

array([[ 2,  5],
       [ 3,  7],
       [ 9,  6],
       [44, 55]])

# Array Resizing

In [50]:
ar

array([ 2,  5,  3,  7,  9,  6, 44, 55])

In [51]:
np.resize(ar,(3,4))

array([[ 2,  5,  3,  7],
       [ 9,  6, 44, 55],
       [ 2,  5,  3,  7]])

In [52]:
np.resize(ar,(2,3))

array([[2, 5, 3],
       [7, 9, 6]])

# Array stacking

In [53]:
# vstack: stacks arrays vertically
# hstack: stack arrays horizontally
# concatenate: concatenate arrays along the specified axis

In [54]:
a1 = np.array([4,2,6])
a2 = np.array([3,6,9])

In [55]:
np.vstack((a1,a2))

array([[4, 2, 6],
       [3, 6, 9]])

In [56]:
np.hstack((a1,a2))

array([4, 2, 6, 3, 6, 9])

In [57]:
concate = np.concatenate((a1,a2),axis=0)


In [58]:
concate

array([4, 2, 6, 3, 6, 9])

In [59]:
concate.reshape(2,3)

array([[4, 2, 6],
       [3, 6, 9]])

# Array Spliting

In [60]:
asr = np.array([1,2,3,4,5,6,7,8,9])

In [61]:
np.split(asr,3)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

# Common Mathematic Operation

In [62]:
a1,a2

(array([4, 2, 6]), array([3, 6, 9]))

In [63]:
np.add(a1,a2)

array([ 7,  8, 15])

In [64]:
np.subtract(a1,a2)

array([ 1, -4, -3])

In [65]:
np.multiply(a1,a2)

array([12, 12, 54])

In [66]:
np.divide(a1,a2)

array([1.33333333, 0.33333333, 0.66666667])

In [67]:
np.power(a1,a2)

array([      64,       64, 10077696])

# Trignometry Functions

In [68]:
ang = np.array([0, np.pi/6, np.pi/4, np.pi/3, np.pi/2])

In [69]:
sin = np.sin(ang)

In [70]:
sin

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [71]:
cos = np.cos(ang)

In [72]:
cos

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

In [73]:
tan = np.tan(ang)

In [74]:
tan

array([0.00000000e+00, 5.77350269e-01, 1.00000000e+00, 1.73205081e+00,
       1.63312394e+16])

In [75]:
np.arcsin(sin)

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [76]:
np.arccos(cos)

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [77]:
np.arctan(tan)

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

 # Exponential and Logrithmic Function

In [78]:
a3 = np.array([3,7,3,56,9,4,1,6])

In [79]:
np.exp(a3)

array([2.00855369e+01, 1.09663316e+03, 2.00855369e+01, 2.09165950e+24,
       8.10308393e+03, 5.45981500e+01, 2.71828183e+00, 4.03428793e+02])

In [80]:
np.log(a3)

array([1.09861229, 1.94591015, 1.09861229, 4.02535169, 2.19722458,
       1.38629436, 0.        , 1.79175947])

In [81]:
np.log10(a3)

array([0.47712125, 0.84509804, 0.47712125, 1.74818803, 0.95424251,
       0.60205999, 0.        , 0.77815125])

# Rounding and Absolute values

In [82]:
a4 = np.array([3.25,2.67,-6.89,4.55,7])

In [83]:
np.round(a4)

array([ 3.,  3., -7.,  5.,  7.])

In [84]:
np.floor(a4)

array([ 3.,  2., -7.,  4.,  7.])

In [85]:
np.ceil(a4)

array([ 4.,  3., -6.,  5.,  7.])

In [86]:
np.abs(a4)

array([3.25, 2.67, 6.89, 4.55, 7.  ])

# Statistical Function

In [87]:
a3

array([ 3,  7,  3, 56,  9,  4,  1,  6])

In [88]:
np.mean(a3)

11.125

In [89]:
np.sum(a3)

89

In [90]:
np.min(a3)

1

In [91]:
np.max(a3)

56

In [92]:
np.std(a3)

17.1277370075559

# Operations on array with different shapes and sizes

In [93]:
ao = np.array([4,5,6])
ap = np.array([[3],[6],[8]])

In [94]:
ao+ap

array([[ 7,  8,  9],
       [10, 11, 12],
       [12, 13, 14]])

# Image Processing

In [95]:
import matplotlib.pyplot as plt

In [96]:
from skimage import io

In [97]:
#image = io.imread("C:/User/afaqx/Downloads/card")

# data normalization

In [98]:
data = np.random.rand(100,3)*10+5

In [99]:
mean = np.mean(data, axis=0)

In [100]:
data.size

300

In [101]:
std = np.std(data,axis=0)

In [102]:
normalized_data = (data - mean)/std

In [103]:
normalized_data[:5,:]


array([[ 1.15808984e+00, -1.59438044e-01,  7.03503525e-01],
       [-8.01778889e-01,  1.49961785e+00, -1.19363419e-03],
       [ 5.84846166e-01,  1.22027701e+00,  1.06329842e-01],
       [ 2.13580877e-01,  6.89493435e-01, -9.49994690e-01],
       [-1.72678996e+00, -6.27652734e-01,  4.38306214e-01]])

# Machine Learning feature scaling

In [104]:
#from sklearn.datasets import load_iris

# Iterating over arrays using loop

In [105]:
ai = np.array([1,2,3,4,5,6,7,8,9])

In [106]:
for items in ai:
    print(items)

1
2
3
4
5
6
7
8
9


In [107]:
ai2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [108]:
for row in ai2:
    for item in row:
        print(item)

1
2
3
4
5
6
7
8
9


# Basic statistics

In [119]:
at = np.array([10,22,34,54,15])


In [120]:
np.mean(at)

27.0

In [121]:
np.median(at)

22.0

In [122]:
np.var(at)  #Variance

247.2

In [123]:
np.std(at)  # standard deviation

15.722595205626837

In [124]:
print(np.max(at))
print(np.min(at))

54
10


# Airports cabs data analysis

In [125]:
taxi = np.genfromtxt('nyc_taxis.csv', delimiter = ',', skip_header = True)

In [126]:
speed = taxi[:,7] / (taxi[:,8] / 3600)

In [127]:
np.mean(speed)

32.24258580925573

In [128]:
rides_feb = taxi[taxi[:,1] == 2 , 1]

In [129]:
np.size(rides_feb)

13333

In [130]:
print(taxi[taxi[:,-3] > 50,-3].size)

16


In [131]:
JFK_rides = taxi[taxi[:,6] == 2, 6]

In [133]:
print(JFK_rides.size)

11832
